### ISSUE TITLE
Support Optional for repository methods

### ISSUE THREAD

**Issue by jbspeakr** [michaellavelle/spring-data-dynamodb#49]
I'd like to use the [Spring Data Support for JDK 8's Optional for repository methods](https://github.com/spring-projects/spring-data-examples/tree/master/jpa/java8). 

Unfortunately, right now this seems not to be supported. Instead there will be an EmptyResultDataAccessException thrown, if your custom-query result is empty...

``` java
org.springframework.dao.EmptyResultDataAccessException: No results found
    at org.socialsignin.spring.data.dynamodb.query.AbstractMultipleEntityQuery.getSingleResult(AbstractMultipleEntityQuery.java:41) ~[spring-data-dynamodb-1.0.1.jar:na]
    at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$SingleEntityExecution.execute(AbstractDynamoDBQuery.java:219) ~[spring-data-dynamodb-1.0.1.jar:na]
    at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:234) ~[spring-data-dynamodb-1.0.1.jar:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:384) ~[spring-data-commons-1.8.1.RELEASE.jar:na]
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:344) ~[spring-data-commons-1.8.1.RELEASE.jar:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.0.8.RELEASE.jar:4.0.8.RELEASE]
    at com.sun.proxy.$Proxy79.findByArticleNumber(Unknown Source) ~[na:na]
```

**Comment by marcbr8** [comment]
+1

**Comment by derjust** [comment]
Please check out [derjust/spring-data-dynamodb](https://github.com/derjust/spring-data-dynamodb/). It is supported in [`spring-data-dynamodb` version 4.2.x](http://search.maven.org/#artifactdetails%7Ccom.github.derjust%7Cspring-data-dynamodb%7C4.2.0%7Cjar) and confirmed by testcase https://github.com/derjust/spring-data-dynamodb/commit/6c5de7ec2995b898ee2e933387ffa7fcfb89aaf7
